name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JavaFX SDK and MSSQL driver
        run: |
          mkdir -p dependencies/javafx-sdk dependencies/sqljdbc
          # Download JavaFX SDK
          curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/23.0.1/openjfx-23.0.1_linux-x64_bin-sdk.zip
          unzip javafx-sdk.zip -d dependencies/javafx-sdk
          # Download MSSQL driver
          rm -f sqljdbc.zip
          curl -L -o sqljdbc.zip https://go.microsoft.com/fwlink/?linkid=2283744
          if ! unzip -tqq sqljdbc.zip; then
            echo "Downloaded SQLJDBC file is invalid."
            exit 1
          fi
          unzip sqljdbc.zip -d dependencies/sqljdbc


      - name: Build JavaFX app
        run: |
          export JAVA_FX_PATH=$(pwd)/dependencies/javafx-sdk/javafx-sdk-23.0.1/lib
          export SQLJDBC_AUTH_PATH=$(pwd)/dependencies/sqljdbc/sqljdbc_12.8/enu/auth/x64
          javac --module-path "$JAVA_FX_PATH" --add-modules javafx.controls,javafx.fxml -cp ".:dependencies/sqljdbc/sqljdbc_12.8/enu/mssql-jdbc.jar" src/Main.java
          jar cvfe MyRestaurantApp.jar RestaurantSystemApp -C src .

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to Azure VM
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}
          AZURE_SSH_PRIVATE_KEY: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${AZURE_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa MyRestaurantApp.jar $AZURE_VM_USER@$AZURE_VM_IP:/home/$AZURE_VM_USER/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r dependencies/sqljdbc/sqljdbc_12.8/enu/auth/x64 $AZURE_VM_USER@$AZURE_VM_IP:/home/$AZURE_VM_USER/sqljdbc_auth
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $AZURE_VM_USER@$AZURE_VM_IP "nohup java -Djava.library.path=/home/$AZURE_VM_USER/sqljdbc_auth --module-path /path/to/javafx-sdk/lib --add-modules javafx.controls,javafx.fxml -jar /home/$AZURE_VM_USER/MyRestaurantApp.jar &"
